# Generated by Django 5.0.7 on 2024-08-06 16:53

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=None, default='avatar.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to=''),
        ),
    ]
